/**
 * @file Polarization.js
 * @description Writing article route for the site.
 * @author Duncan Grubbs <duncan.grubbs@gmail.com>
 * @version 0.1.0
 */

import React, { Component } from 'react';

import NavBar from '../../components/NavBar';

class Polarization extends Component {
  componentDidMount() {
    const scrollTracker = document.getElementById('scroll-tracker');
    document.addEventListener('scroll', (evt) => {
      const limit = Math.max(
        document.body.scrollHeight,
        document.body.offsetHeight, 
        document.documentElement.clientHeight,
        document.documentElement.scrollHeight,
        document.documentElement.offsetHeight
      );
      const percent = (evt.target.scrollingElement.scrollTop + document.documentElement.clientHeight) / limit;
      const pixCalc = (document.documentElement.clientWidth) * percent;
      scrollTracker.style.width = `${pixCalc}px`;
    });
  }

  render() {
    return (
      <div>
        <NavBar />
        <div id="scroll-tracker" />
        <div className="writing">
          <p className="writing__title">A Growing Divide: America&rsquo;s Struggle with Polarization</p>
          
          <p className="writing__para">America has always championed open political discourse and diversity of beliefs, but recently, scholars have begun to see a concerning trend in the movement of Americans&rsquo; beliefs. This trend can be described as political polarization, and the resulting changes have undermined healthy political discussions and thought in the American public. Without these key factors of democracy, the U.S. government has become much more partisan and has moved slower to provide basic resources and policy to the public. While there are many proposed causes of these issues, research points to the popularization of the internet and the resulting changes to the media as a large factor in the increasing severity of this political polarization.</p>
          
          <p className="writing__para">Polarization is the process in which things move closer to the opposite ends of a scale. In the context of politics, polarization can be defined as the movement of the average beliefs of Americans away from the center of the political ideology spectrum. Since the United States has a fundamentally two-party system, we can define political beliefs as either leaning left or leaning right. Because of this binary belief system, there can be a scale that ranges from the most extreme beliefs on the right, to the most extreme beliefs on the left. In other words, the scale ranges from most conservative to most liberal. Polarization is when the average beliefs of self-identifying conservatives or liberals fall farther from the center of the scale than they had before. This could mean citizen&rsquo;s beliefs moving from moderate to slightly less moderate, or from relatively neutral to an extreme.</p>
          
          <p className="writing__para">For polarization to occur, &ldquo;the simultaneous presence of opposing or conflicting principles, tendencies, or points of view&rdquo; (Fiorina and Abrams 566) is necessary. It is difficult for the average beliefs of a population to shift farther from each other if there are no differences between them in the first place. If there is common ground, many of the causes of polarization fail to gain traction. Luckily, determining whether there is a simultaneous presence of opposing principles in a political system is simple (Fiorina and Abrams). Throughout most of America&rsquo;s history, there have been conflicting principles, and therefore a political environment that is ripe for polarization. Unsurprisingly, America has gone through some highly polarized periods, whether it was the Civil War or the race riots of the 90&rsquo;s. In contrast, the times when America was least polarized were often when there was a common enemy or problem. For example, during World War II&#8210;and just after the 911 terrorist attacks&#8210;the country was very united. Fundamentally, although America&rsquo;s social and political systems are not always polarized, they allow for polarization and sometimes even harbor it.</p>
          
          <p className="writing__para">One of the large questions I want to answer is whether or not America is becoming more polarized. By the definition of polarization, America has always moved towards being more unified or divided. There has never been a time when Americans&rsquo; beliefs were not shifting. The issue now surrounds the question of if there is a growing gap between the average beliefs of Americans. While there is data that can show recent spikes in ideological divides, &ldquo;In contrast to judging levels of polarization, identifying trends in polarization is an easier task&rdquo; (Fiorina and Abrams 567). It is hard to say exactly how polarized we are as a nation currently, but it easier to argue that we are becoming more polarized over time. Because of this, I will answer my question in terms of a trend, and not attempt to describe the current level of polarization as high or low. When we look at the data, it is clear that &ldquo;Republicans and Democrats are more divided along ideological lines &ndash; and partisan antipathy is deeper and more extensive &ndash; than at any point in the last two decades&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;). This division manifests itself in many ways, some of which include: partisan antipathy, ideological consistency, changes in personal life, and diminishing compromises.</p>
          
          <p className="writing__para">Americans&rsquo; beliefs are homogenizing. Over time, &ldquo;the correlation of peoples&rsquo; views with their party identification has increased significantly&rdquo; (Gentzkow 12). In 2014, &ldquo;92% of Republicans [were] to the right of the median Democrat, and 94% of Democrats [were] to the left of the median Republican.&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;). While this data is hard to argue with, it is important to look at previous years to examine a trend, rather than just the current degree of polarization. In 1994, around half of a surveyed population took an equal number of conservative and liberal positions. Today, only &ldquo;39% of Americans currently take a roughly equal number of liberal and conservative positions&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;). Americans are falling into one of two political parties more often now, and staying there. Shared beliefs across political parties are slowly disappearing as citizen&rsquo;s views fall more under party lines. All of these trends point to a growing divide in political beliefs. However, only in recent years have these trends seen immense growth. Because of this, it is hard to say for sure if this polarization is truly a long-term trend, but it has been getting significantly more severe throughout the past two decades.</p>
          
          <p className="writing__para">While ideological divisions &ldquo;are greatest among those who are the most engaged and active in the political process&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;), there are still consequences that affect the nation as a whole. The effects of this political polarization are widespread and severe. According to the Pew Research Center, partisan antipathy is the highest it has been in decades. This affects social life, policy, and the future health of our country. Over the long history of the United States, we have overcome many challenges, including slavery, war, and economic depression. However, even now, we still face problems like the rising cost of healthcare and education, drug addiction, and natural disasters. Without bipartisan agreements and policy-making, very little can get accomplished. In the government, politicians represent their constituents, but because there is little agreement amongst the public, there is often little agreement amongst the politicians representing them. This leaves the country in a perpetual state of disrepair. America is in the process of solving major issues that cross party lines such as abortion, health care, gun control, and immigration. Even when negotiating these traditionally bipartisan issues, lawmakers are slow to find compromises because of the extreme beliefs of the citizens they represent. For example, the popular views on healthcare are almost all that it should be entirely in the public sector, or that it should be totally privatized. Without bipartisan agreements, these issues will remain unsolved and the American public will remain in need.</p>
          
          <p className="writing__para">Another consequence of this growing division is the election of less moderate officials. &ldquo;Both Republican and Democratic candidates are saying things that their predecessors would have never dreamed of&rdquo; (&ldquo;Roots of American political polarization&rdquo;). During the 2016 presidential race, &ldquo;Republican candidate Mike Huckabee suggested that he might be willing to use the American military to prevent women from getting abortions&rdquo; (&ldquo;Roots of American political polarization&rdquo;). Previous to this, such an extreme statement wouldn&rsquo;t have even been considered by mainstream candidates. Just last year, Donald Trump was elected as president, and Republican voters &ldquo;applauded proposals to build fences on the border and to ban Muslims&rdquo; (Gentzkow 2). Around half the population voted for him, and the other half of the population &ldquo;decided once and for all that those on the other side of the political divide didn&rsquo;t just have different priorities, didn&rsquo;t just hold different opinions, but were out to destroy the country and everything it stands for&rdquo; (Gentzkow 2). The connections between divisions in the public and the election of more radical officials are clear. Unfortunately, the social ramifications of these candidate choices are already becoming very evident.</p>
          
          <p className="writing__para">Some of the largest negative effects of this polarization are the social changes sweeping the nation. Along with affecting the government, &ldquo;divides in the political sphere also permeate the everyday lives of Americans&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;). One of these changes is the geographical movement of citizens based on political affiliation. &ldquo;Not only do many of these polarized partisans gravitate toward like-minded people, but a significant share express a fairly strong aversion to people who disagree with them&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;). People are choosing where to live and who to associate with based on political beliefs. One of the most extreme manifestations of these social divisions occurred at a far-right rally in Charlottesville, North Carolina when a man drove a car into a group of protesters, killing one. &ldquo;In Charlottesville and beyond, people were grappling with the blatant display of attitudes that many believed had been buried, but the extremists who rallied were newly energized and planning their next moves&rdquo; (Astor, et al). While some may have thought those attitudes were &ldquo;buried&rdquo;, it is possible that they simply weren&rsquo;t aware of them because of the geographical and social barriers between people of different political affiliations. Now, ideological disagreements are settled through violence and extremism which only builds on the partisan antipathy that was already present. These social changes are some of the most obvious effects of this polarization and will be key in the education and unification of the public when it comes to solving this problem.</p>
          
          <p className="writing__para">There are many proposed causes of this division. However, within the discourse community, the most agreed upon causes are the internet, the media, and the connection between them. The growth of the internet contributed to two major things, one was the availability of radical information and ideas, and the other was the formation of ideological echo-chambers. Because anyone with an internet connection can access almost any information they want, there has been a spread of radical beliefs and political thought that would have otherwise not spread. Traditionally, one person could spread radical beliefs through physical interaction or possibly through a small local newspaper or radio station, reaching no more than a few thousand people. Even then, the ideas would rarely catch on because of their small audience and radical nature. Now with the internet, a single person has the potential to influence millions of people.</p>
          
          <p className="writing__para">The other major issue with the internet is that it allows for ideological echo-chambers. The media uses these echo-chambers as a way of limiting their audience. The more people rely on technology, specifically the internet, to get their information, the easier it is for those information providers to cater to exactly what each individual wants to see. This targeting of information creates online echo-chambers. Recommended news stories, social media posts, and videos are all based on what you have already viewed. &ldquo;In trying to show us content we will click on, Google&rsquo;s personalized search results and Facebook&rsquo;s personalized news feeds screen out content we are most likely to disagree with and create a comfortable bubble of like-minded information&rdquo; (Gentzkow 18). There is rarely contradictory or new information entering people&rsquo;s mind, and the &ldquo;unplanned, unanticipated encounters [that are] central to democracy itself&rdquo; (Sunstein 9) simply do not occur. Before the internet, the media had to pander to a wide audience. A Republican would still happen to come across liberal viewpoints while reading the newspaper or watching the news and vice versa. Regardless if they disagreed, they were still exposed to those ideas. Now that people are only seeing information that they agree with, their decisions are becoming less rational and more biased. These decisions are now becoming more influential too, as some research suggests that politically consistent citizens have &ldquo;more intense political engagement&rdquo; (&ldquo;Political Polarization in the American Public&rdquo;) compared to less politically consistent citizens. Not only are political beliefs becoming homogenized within parties, but those same beliefs are being expressed now more than ever. Due to this, data regarding political polarization now shows significantly higher levels of polarization than older data on the same subject.</p>
          
          <p className="writing__para">The problem with the causes of this divide is that they are, for the most part, not politically motivated. Fundamentally, they stem from companies and individuals wanting to generate the most profit. Advertisers want to know their exact audience, and news stations want to have good ratings. The more they can homogenize their audience, the more profit they can make. This is because the less controversial they are within the eyes of their own audience, the better their ratings are, and the more they are favored over competitors that may offer differing viewpoints. Having an audience that agrees with you completely can also increase the likelihood of viewers buying into premium services or even donating. Fundamentally, this issue of polarization will not be solved by the companies and people who are responsible for causing it, nor the people responsible for regulating those companies. At first, one might think that because the motivation is profit, the government is responsible for fixing the problem. However, even the government has limited power because this isn&rsquo;t an issue of false information or illegal broadcasting practices. The true way to solve this problem is through education of the public. The more we can become aware of this issue, and why it is happening, the more we can be active in solving it. Since most of the negative effects are on us, there is an urgency and importance that can be shared across party lines.</p>
          
          <p className="writing__para">While not all scholars agree, there is at least a very contemporary consensus that political polarization is increasingly worse in America. Along with a significant amount of data and examples that directly show increasing political division, there are also clear connections between the causes and effects of this issue. Although some argue that the trends in polarization are simply misinterpretations of data that has &ldquo;little or no relevance to the question&rdquo; (Fiorina and Abrams 567), their writing was often published before the large Pew Research Center study that has provided the most compelling evidence to date for increasing polarization. Since this subject is still so new, there have been few proposed solutions, but I believe that through educating the public about these issues and their causes, the solution for easing the polarization can fall in the actions of citizens. While the government can play a role, the citizens who are becoming so divided have the most power to change that. This solution starts with the education of politically active citizens and young people. As a country, it is vital that we come together in a time like this to diminish the consequences of this polarization and return our country to a state of political and social efficiency. While we may not make the choice to enter into ideologically echo-chambers on the internet, we can make ourselves aware of how to exit them. We can deliberately engage in media sources we may not have looked at before, or have discussions with people who may not share the same political beliefs. We can broaden the range of things that influence us, and help the country in doing it. Hopefully, our understanding of this issue can grow as time goes on, and we can unite the country to fight political division.</p>
          
          <p className="writing__para">Works Cited</p>
          
          <p className="writing__para">Fiorina, Morris P., and Samuel J. Abrams. &quot;Political polarization in the American public.&quot; Annu.<br />
          Rev. Polit. Sci. 11 (2008): 563-588.</p>
          
          <p className="writing__para">Gentzkow, Matthew. Polarization in 2016. Stanford University, 2016.</p>
          
          <p className="writing__para">&quot;Roots of American political polarization.&quot; UWIRE Text, 29 Sept. 2015, p. 1. Infotrac Newsstand. Accessed 1 Nov. 2017.<br />
          N/A. Political Polarization in the American Public. Pew Research Center. 2014.</p>
          
          <p className="writing__para">Astor, Maggie, et al. &ldquo;A Guide to the Charlottesville Aftermath.&rdquo; The New York Times, The New York Times, 13 Aug. 2017.<br />
          </p><p className="writing__para">Sunstein, Cass R. Republic.com. Princeton University Press, 2007.</p>
        </div>
      </div>
    );
  }
}

export default Polarization;